### ISSUE TITLE
version 2.6.3 isn't on maven central

### ISSUE THREAD

**Issue by DaniDipp** [agrevster/pocketbase-kotlin#11]
I'm unable to download version 2.6.3 and according to [Sonatype](https://search.maven.org/artifact/io.github.agrevster/pocketbase-kotlin), the latest version is 2.6.2 from August 29th.

[publish-to-maven-central #22](https://github.com/agrevster/pocketbase-kotlin/actions/runs/11151716629) seems to have completed successfully, so did something else happen to it?

**Comment by agrevster** [comment]
Yeah, that’s weird. I thought I pushed those out to central. I’ll take a look.

**Comment by agrevster** [comment]
I just re-ran the publish job and releaced all the artifacts. I’ll check back in an hour and see if they’re on central.

**Comment by agrevster** [comment]
It looks like I forgot to hit release last time. 2.6.3 is on central now. Sorry for any inconvenience.

**Comment by DaniDipp** [comment]
Thanks for looking into it and the quick fix! 👏
