### ISSUE TITLE
create records adds " to the values

### ISSUE THREAD

**Issue by EduFdezSoy** [agrevster/pocketbase-kotlin#8]
When doing 
```kotlin
    suspend fun createChapter(): Chapter {
        val response = client.records.create<Chapter>(
            "test",
            //A workaround to the limitations on JSON with multipart form data
            mapOf(
                "title" to Json.encodeToJsonElement(recordToCreate.title),
                // ...
```
where `recordToCreate.title` is `title = "test from android"`
it saves in pocketbase with a pair of "
![image](https://github.com/user-attachments/assets/97e83b47-d3c8-468b-8883-3a0adbc42091)

its not too bad for text but when doing email validation or some other pattern it fails cause the "

**Comment by EduFdezSoy** [comment]
same behavior when doing ```"text".toJsonPrimitive()```

**Comment by agrevster** [comment]
I’ll look into it

**Comment by agrevster** [comment]
I explicitly added the quotes to the test... odd
https://github.com/agrevster/pocketbase-kotlin/blob/f650e2baec6380bd0b005a8b3870eeaa6ed6e83a/src/commonTest/kotlin/services/RecordServiceFileUpload.kt#L105
You’re right that’s not how it’s supposed to be.

**Comment by agrevster** [comment]
Fixed @EduFdezSoy  
68fbf6a17972aa6f3a2545669901f6919870c24c
