### ISSUE TITLE
Expand list of relations

### ISSUE THREAD

**Issue by Turtlepaw** [agrevster/pocketbase-kotlin#9]
Hi, how do I expand a list of relations? (e.g. list of users)

I've tried using this:

```kotlin
data class ExampleRecord(/*...*/) : ExpandRecord<List<User>>()
```

but get this error:

```
Type argument is not within its bounds: should be subtype of 'io. github. agrevster. pocketbaseKotlin. models. Record'.
```

It seems that this SDK isn't designed to handle a list of relations, will this ever be supported in the future?

**Comment by agrevster** [comment]
Thats right! Pocketbase does support multiple relations. I’ll look into adding that.

**Comment by agrevster** [comment]
It is being worked on @Turtlepaw
